// Generated by .smithers/lib/ddd/generateUiModules.ts - do not edit.
// One ticket per open gap (features.json broken/partial/missing* + each missing[] item).
export const ticketsBacklog: { path: string; kind: string; status: string; priority: string; updatedAtMs: number; featureId: string; featureTitle: string; content: string }[] = [];
