// Generated by .smithers/lib/ddd/generateUiModules.ts - do not edit.
export const docsContent: { path: string; title: string; level: "product" | "technical"; content: string }[] = [
  {
    "path": "overview.md",
    "title": "Product specification",
    "level": "product",
    "content": "# Product specification\n\nThis starter spec is intentionally empty. Run docs-driven-development to describe the target repository.\n"
  }
];
export type DocsContentEntry = (typeof docsContent)[number];
